# -*- coding: utf-8 -*-
"""For.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e7gX4luC8ajosfHajT41Xwe6CQ-rrgUa
"""

#Faça um programa que peça 10 números inteiros, calcule e mostre a
#quantidade de números pares e a quantidade de números impares.

valores = []

for n in range(10):
  numero = int(input(f"Digite o {n + 1}numero inteiro: "))
  valores.append(numero)

for valor in valores:
  if valor % 2:
    print(f"Valor impar: {valor}")
  else:
   print(f"Valor par: {valor}")