# -*- coding: utf-8 -*-
"""While.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rjtvTWFlQXnU9KQtbDaz2RmIUNArqHgC
"""

#Um funcionário de uma empresa recebe aumento salarial anualmente.
#Sabe-se que: Esse funcionário foi contratado em 1995, com salário inicial de R$
#1.000,00; Em 1996 recebeu aumento de 1,5% sobre seu salário inicial; A partir de
#1997 (inclusive), os aumentos salariais sempre correspondem ao dobro do
#percentual do ano anterior. Faça um programa que determine o salário atual desse
#funcionário. Após concluir isto, altere o programa permitindo que o usuário digite o
#salário inicial do funcionário.

ano = 1996
salarioInicial = 1000
percentual = 0.015

salarioInicial += salarioInicial * percentual

print(f"Salario atual em {ano} = {salarioInicial}")

while ano != 2024:
  ano += 1
  percentual *= 2
  salarioInicial += salarioInicial * percentual
  print(f"salario atual em {ano} = {salarioInicial}")